Repository ADimoska/SOMASExtended, pull requests merged in 2024-12, with the labels that each got.

#89 54 add game playback info
  .gitignore
  agents/ExtendedAgent.go
  agents/MI_256_v1.go
  common/IExtendedAgent.go
  common/team.go
  gameRecorder/AgentRecord.go
  gameRecorder/DataRecorder.go
  gameRecorder/DataVisualizer.go
  gameRecorder/TeamRecord.go
  go.mod
  go.sum
  main.go
  server/EnvironmentServer.go
Labels: high priority

#97 BugFix - StateContributionToTeam and StateWithdrawalToTeam
  agents/ExtendedAgent.go
  common/IExtendedAgent.go
  server/EnvironmentServer.go
Labels: bug, high priority, simple

#88 Fix allocateAoAs()
  agents/ExtendedAgent.go
  server/EnvironmentServer.go
Labels: bug, enhancement

#99 Upgrade allocateAoA()
  server/EnvironmentServer.go
Labels: bug, enhancement

#90 Remove agent 'Decide' functions
  agents/ExtendedAgent.go
  common/IExtendedAgent.go
Labels: pending review

#116 Bug Fix: skip record turn info for agents not in a team
  server/EnvironmentServer.go
Labels: bug

#114 Game Visualization & Various bug fixes (54 add game playback info)
  agents/MI_256_v1.go
  gameRecorder/CommonRecord.go
  gameRecorder/DataRecorder.go
  gameRecorder/DataVisualizer.go
  main.go
  server/EnvironmentServer.go
  visualization_dashboard.py
Labels: high priority

#120 Audit Punishment Helper
  common/ArticlesOfAssociation.go
  common/FixedAoA.go
  common/Team1AoA.go
  common/Team2AoA.go
  common/Team4AoA.go
  common/Team5AoA.go
  server/EnvironmentServer.go
Labels: high priority

#119 Agent Names
  agents/ExtendedAgent.go
  common/IExtendedAgent.go
  main.go
Labels: enhancement, in progress, pending review

#122 Fix Team Common Pool being reset to 0 per n threshold turns
  server/EnvironmentServer.go
Labels: high priority

#121 Visualization python script bug fix
  main.go
  server/EnvironmentServer.go
  visualization_dashboard.py
Labels: bug

#126 GitHub action: run main.go 10 times
  .github/workflows/run-main-go.yml
Labels: enhancement, high priority

#128 Update orphan pool and fixed seg fault in team1AoA
  agents/ExtendedAgent.go
  common/IExtendedAgent.go
  common/Team1AoA.go
  server/EnvironmentServer.go
  server/OrphanPool.go
  test/orphan_test.go
Labels: enhancement

#129 Emergency Safety Check
  server/EnvironmentServer.go
Labels: bug, high priority

#124 Add Team 1 Agent v0.1.8
  agents/MI_256_v1.go
  agents/Team1Agent.go
  common/IExtendedAgent.go
  common/Team4AoA.go
  main.go
  server/EnvironmentServer.go
Labels: enhancement, high priority

#139 Moved ApplyPunishment
  server/EnvironmentServer.go
Labels: bug, high priority

#155 No Time to Die
  .github/workflows/run-gotest.yml
  test/orphan_test.go
  test/team1_aoa_test.go
Labels: bug, invalid, high priority
